### ISSUE TITLE
update KDE runtime to 5.12

### ISSUE THREAD

**Issue by eszlari** [flathub/io.github.Cockatrice.cockatrice#15]

**Comment by tooomm** [comment]
Can you let us know why that would be helpful or what it does change?

**Comment by eszlari** [comment]
You would get Qt 5.12 (with updates & bugfixes, likw HiDpi, Wayland). New users would not have to download 5.9 and 5.12. And you help the maintainers, because they can focus on 5.12.

**Comment by subpop** [comment]
FWIW, in Fedora 29, we already build Cockatrice against Qt 5.11. So I'm in favor of updating the runtime to 5.12.

**Comment by tooomm** [comment]
PR created, thanks for the ticket @eszlari!
