### ISSUE TITLE
Update protobuf

### ISSUE THREAD

**Issue by tooomm** [flathub/io.github.Cockatrice.cockatrice#20]
Currently, v3.4.0 is used:
https://github.com/flathub/io.github.Cockatrice.cockatrice/blob/master/io.github.Cockatrice.cockatrice.json#L35

As of now, 3.7.0 is available: https://github.com/protocolbuffers/protobuf/releases

**Comment by subpop** [comment]
Are there breaking changes between 3.4 and 3.7 that you're aware of? Does Cockatrice call out a required minimum version?

**Comment by tooomm** [comment]
>Are there breaking changes between 3.4 and 3.7 that you're aware of?

Reading their changelogs, I couldn't find anything special. Besides that they require C++11 since [v3.6](https://github.com/protocolbuffers/protobuf/releases/tag/v3.6.0)

>Does Cockatrice call out a required minimum version?

We ask for 3.1, but Cockatrice compiles with various versions just fine.
We use 2.6, 3.5 and 3.6 for example depending on what's easily available on the CI environments.

For flatpak we can upgrade to [3.6.1](https://github.com/protocolbuffers/protobuf/releases/tag/v3.6.1) instead, too.

**Comment by subpop** [comment]
Sounds good to me. You should be a committer now, according to https://github.com/flathub/flathub/issues/906. Are you able to commit directly to master?

**Comment by tooomm** [comment]
Yes, that works fine @subpop
