### ISSUE TITLE
update KDE runtime to 5.15

### ISSUE THREAD

**Issue by eszlari** [flathub/io.github.Cockatrice.cockatrice#34]

**Comment by subpop** [comment]
@tooomm any objection to a change like this? Is upstream ready to support an updated KDE runtime?

**Comment by ebbit1q** [comment]
yeah, I fixed all the warnings in https://github.com/Cockatrice/Cockatrice/pull/4027 and for 5.15.1 I fixed the warnings in https://github.com/Cockatrice/Cockatrice/pull/4102 both would have worked on release builds though.
