### ISSUE TITLE
Needs a screenshot 

### ISSUE THREAD

**Issue by LeandroStanger** [flathub/io.github.Cockatrice.cockatrice#5]
This app needs one or more screenshots added to the appdata, otherwise it looks a bit rubbish in software stores.

**Comment by LeandroStanger** [comment]
![captura de tela de 2018-02-07 21-54-33](https://user-images.githubusercontent.com/26097419/35948061-d32bef1a-0c51-11e8-9e8f-de36a85ee5f6.png)

**Comment by subpop** [comment]
Thanks for the issue!

@tooomm, do you guys have any official-ish screenshots we can use?

**Comment by tooomm** [comment]
We don't have that currently
And I guess we wouldn't want to use one with copyrighted art in them.

Thanks for opening the issue @LeandroStanger and pingin me @subpop.
Will see what we can do.

**Comment by LeandroStanger** [comment]
![captura de tela de 2018-02-09 16-24-41](https://user-images.githubusercontent.com/26097419/36043234-c0be38c8-0db5-11e8-944b-e54a7f39e14b.png)

**Comment by tooomm** [comment]
And below there is just more text? Sorry I don't run linux and have no idea. 😄

**Comment by LeandroStanger** [comment]
![captura de tela de 2018-02-09 17-38-22](https://user-images.githubusercontent.com/26097419/36046427-0af16500-0dc0-11e8-86c3-7404adf285be.png)

**Comment by tooomm** [comment]
self note, style in https://github.com/flathub/io.github.Cockatrice.cockatrice/blob/master/io.github.Cockatrice.appdata.xml should be this:
```
	<screenshots>
		<screenshot>
			<image type="source">https://site.com/image1.png</image>
		</screenshot>
		<screenshot>
			<image type="source">https://site.com/image2.png</image>
		</screenshot>
	</screenshots>
```

**Comment by tooomm** [comment]
I'm looking into adding some screenshots.

Can we have a screenshots folder in the repo to use that as image source? @subpop 
Or do you have any other idea where to host the pictures?

**Comment by subpop** [comment]
Are there any screenshots hosted on cockatrice.github.io? Those would be ideal. Already hosted on upstream's website and we could link to them in the Appstream data file directly.

**Comment by tooomm** [comment]
No there are no screens there, I have a few at hand now (made on linux) that show a free open source card game. 👍

Do you think it's a bad idea to include them in the repo here to have everything in one place?

**Comment by tooomm** [comment]
Do you like the screens @LeandroStanger, and do they showcase the app properly?

**Comment by LeandroStanger** [comment]
@tooomm Liked

**Comment by tooomm** [comment]
Feel free to let us know how the end result looks like and if you like it once it's deployed @LeandroStanger
