### ISSUE TITLE
[when new frontend out of beta] add link to flathub subpage in repo

### ISSUE THREAD

**Issue by tooomm** [flathub/io.github.Cockatrice.cockatrice#7]
Currently the link would be:
https://beta.flathub.org/apps/details/io.github.Cockatrice.cockatrice

**Comment by tooomm** [comment]
Beta got officially released and is running as main page.
Can you update the repo info on the top, please @subpop?

The link is: https://flathub.org/apps/details/io.github.Cockatrice.cockatrice

**Comment by subpop** [comment]
Updated the README with a link to the application details.

**Comment by tooomm** [comment]
Oh, good catch. 👍 
Wasn't aware of that old link in the README to the app overview... I assume because no app pages at that time existed. 😄 

But I was speaking about this originally:
![untitled](https://user-images.githubusercontent.com/9874850/38503528-9d3343fe-3c12-11e8-9317-feb90a808f37.png)

Also, you did remove the repo description. Was that intentional?

**Comment by subpop** [comment]
I didn't remember there being a description in the first place. That screenshot looks like the upstream cockatrice repository. That reminds me that we should update the links in the Cockatrice (upstream) wiki.

**Comment by TingPing** [comment]
I removed it. No package repos on flathub has descriptions, it is just more useless text to maintain.

**Comment by subpop** [comment]
To that end, the Flathub repos on Github are not a place where users are expected to come to discover software. It's where us maintainers come to maintain and develop. I see @TingPing's point in this case. We know what Cockatrice is. There's no reason to try and maintain links for user discoverability.
